### ISSUE TITLE
Only Davinci model works

### ISSUE THREAD

**Issue by wuzimi** [sean1832/GPT-Brain#9]
I tried to use other models to generate answers and failed. Only Davinci works.
Is anything wrong with my operation? Thanks!

**Comment by sean1832** [comment]
Hi there! It's possible that your response is too long for some of the other models to generate answers, while Davinci supports up to 4000 tokens, other models only support up to 2048 tokens. This means that if your input contains more than 2048 tokens, those models will not be able to generate a response.

However, it's difficult to say for certain what might be causing the issue without more information about your specific use case. If you want to check whether your input is hitting the token limit, you can try going to Advanced Mode and disabling the "stream" toggle and try again. This will show you the error message.

If you're still having trouble, feel free to provide more details about your operation and we can try to troubleshoot further.
